version: 2.0
jobs:
  build:
    docker:
      - image: gcc:latest
    working_directory: ~/work
    steps:
      - checkout
      - run: 
          name: Update OpenCV
          command: 'apt-get install libopencv-dev'
      - run: make LIBSO=1 -j 8
      - run: |
          ulimit -c unlimited
          ./darknet
      - run:
          command: |
            mkdir -p /tmp/core_dumps
            cp core.* /tmp/core_dumps
          when: on_fail
      - store_artifacts:
          path: /tmp/core_dumps